### ISSUE TITLE
chef-squid

### ISSUE THREAD

**Issue by pearcec** [oriuminc/vagrant-ariadne#2]
Hey @patcon, Here is a recipe you might benefit from easily.

xforty/chef-squid@446a441ae9d060a0e2403bdbaf8b220f9f5337be 

Have a good weekend.

**Comment by patcon** [comment]
No way! That's awesome pearce! Had you tried it with drush_make? I'd been experimenting with squid on the VM a few months ago, but for whatever reason, I was hitting a brick wall trying to get it working with drush_make, even following that [blogpost for drush/squid setup](http://reluctanthacker.rollett.org/using-squid-caching-server-drush-module-downloads). It was odd. `drush dl` worked fine, and hit the cache, but `drush make` only resulted in `TCP_REFRESH_MISS` (I believe).

I've figured out squid a little more since then, but at the time I wasted quite some time. It was particularly frustrating because OSX squidman worked fine outta the box, but I couldn't tease out the important bits to configure the same.

Anyhow, thanks again. I'll try it out and see if a shared folder for cache will work (I think the squidman is newer than the apt package though...)

**Comment by pearcec** [comment]
Yea we use it specifically because of drush make.  I didn't do anything magically.  Stock squid.  Then set the environment variable.  Shared folder attribute would be cool.  If you code it up I will merge in a pull request.

----- "Patrick Connolly" reply@reply.github.com wrote:

> From: "Patrick Connolly" reply@reply.github.com
> To: "Christian Pearce" pearcec@xforty.com
> Sent: Saturday, February 18, 2012 4:56:38 PM GMT -05:00 US/Canada Eastern
> Subject: Re: [ariadne] chef-squid (#2)
> 
> No way! That's awesome pearce! Had you tried it with drush_make? I'd
> been experimenting with squid on the VM a few months ago, but for
> whatever reason, I was hitting a brick wall trying to get it working
> with drush_make, even following that [blogpost for drush/squid
> setup](http://reluctanthacker.rollett.org/using-squid-caching-server-drush-module-downloads).
> It was odd. `drush dl` worked fine, and hit the cache, but `drush
> make` only resulted in `TCP_REFRESH_MISS` (I believe).
> 
> I've figured out squid a little more since then, but at the time I
> wasted quite some time. It was particularly frustrating because OSX
> squidman worked fine outta the box, but I couldn't tease out the
> important bits to configure the same.
> 
> Anyhow, thanks again. I'll try it out and see if a shared folder for
> cache will work (I think the squidman is newer than the apt package
> though...)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/myplanetdigital/ariadne/issues/2#issuecomment-4037683

## 

xforty technologies 
Christian Pearce 
888-231-9331 x1119 
http://xforty.com

**Comment by patcon** [comment]
Sounds good. I'be since realized that I think drush favours wget over curl
if its available (or vice versa) so it might have been that. I can
accommodate that.

And as for shared folder, I can edit the readme to explain what goes in the
vagrantfile. MacBook broken but will submit when up and running
On Feb 20, 2012 9:31 AM, "Christian Pearce" <
reply@reply.github.com>
wrote:

> Yea we use it specifically because of drush make.  I didn't do anything
> magically.  Stock squid.  Then set the environment variable.  Shared folder
> attribute would be cool.  If you code it up I will merge in a pull request.
>

**Comment by patcon** [comment]
Ref: mattray/squid-cookbook#2

**Comment by patcon** [comment]
Now that drush caching is in place, I can't think of a significant advantage this would confer... am I wrong on that? Like do you guys at @xforty find you're seeing gains from it often?

EDIT: Closing for now, but I'd love to hear a reason to re-open :)

**Comment by fluxsauce** [comment]
@patcon agree, no practical advantage of squid at this point.
