### ISSUE TITLE
pear failing

### ISSUE THREAD

**Issue by calvinte** [oriuminc/vagrant-ariadne#5]
fix:

``` sh
vagrant ssh
sudo pear upgrade --force Console_Getopt
sudo pear upgrade --force pear
sudo pear upgrade-all
sudo pear channel-discover pear.drush.org
sudo pear channel-discover pear.phpunit.de
```

**Comment by patcon** [comment]
Ah I actually figured out how to fix this, but unsure why it happens. Seems to only happen in chef 0.10.10, but not 0.10.8. something to do with channel-info being executed somewhere before it should be, and so pear errors out.
https://github.com/myplanetdigital/ariadne/blob/c519fa854c6cd99ca1db8bf7c46e8f98b395c1ed/Vagrantfile#L48

Fixed in next push
