### ISSUE TITLE
To sudo or not to sudo? That is the question.

### ISSUE THREAD

**Issue by nerdcorenet** [oriuminc/vagrant-ariadne#61]
I'm trying to follow the README on Ubuntu 12.04 Precise Pangolin (AMD64). As an unprivileged (non-root) user I do not have write access to /usr/local/rvm and cannot install rvm without changing ownership of /usr/local. As root I can install rvm into /usr/local/rvm but then as root I cannot seem to fire the .rvmrc file from Ariadne. As the unprivileged user the .rvmrc file is caught by rvm when I change to the ariadne directory, but again I do not have write access to /usr/local/rvm and the script starts to fail on each download.

I could run through the entire README as root if I could just figure out how to get the .rvmrc file to execute.

Any help greatly appreciated.

**Comment by patcon** [comment]
Ah I think you'd want to look into the rvm docs to find out how to install it for a user. As far as I know, that's the rrecommended way. You'll want to go the _Single-User installations_ method, I'd say:
https://rvm.io/rvm/install/

I've been meaning the simplify the rvmrc file and pull some things out of it (since it seems to try to do too much); See #42. This might solve the issue, but single-user rvm install would be what's supported.

I'm going to close this, since it sounds like its outside the scope of support, but feel free to re-open if there's a good reason to have rvm installed as root and I'm missing it :)
