### ISSUE TITLE
Bundler fails to install, gems never loaded after moving to Ariadne gemset on Ubuntu 12.04

### ISSUE THREAD

**Issue by mparker17** [oriuminc/vagrant-ariadne#63]
When I `cd` into the Ariadne directory, I get the following error:

```
mparker17@mcomp5:~/Repositories % cd ariadne 
Using /home/mparker17/.rvm/gems/ruby-1.9.3-p194 with gemset ariadne
Installing Bundler via Rubygems...
ERROR:  Loading command: install (LoadError)
    cannot load such file -- zlib
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Commands::InstallCommand
Installing bundled gems via Bundler...
ERROR: Gem bundler is not installed, run `gem install bundler` first.
Activating rubygems-bundler...
ERROR:  While executing gem ... (RuntimeError)
    Unknown command regenerate_binstubs
mparker17@mcomp5:~/Repositories %
```

The gemsets are never loaded and subsequent calls to `vagrant up` fail.

The 1.1.0 tag worked fine, but the 1.2.0 and all later tags, and the master and develop branch HEADs all have this error. Running git-bisect between tags 1.1.0 and 1.2.0 for a bit resulted in the following analysis:

```
a863d365cf35448391bb0b173e2bf83203416cd5 is the first bad commit
commit a863d365cf35448391bb0b173e2bf83203416cd5
Author: Patrick Connolly <patrick.c.connolly@gmail.com>
Date:   Fri Aug 24 10:23:24 2012 +0200

    Moved to using ariadne gemset rather than unique 1.9.3 ruby sandbox. Removed all development gems until actually utilized.

:100644 100644 4c428a6d2b5859b628bb5f1d40e7b8be3f772a7f 9abbcc3f3f163b6c100737c7b1e7f32411a76fda M  .rvmrc
:100644 100644 307dcd557cd34a3ae99040a6789b79248b1cb95f 3669f2c2164894c61a1eef014a50347c81307846 M  Gemfile
:100644 100644 f8a1afdbcfa147108c4df38ec16c07f7dd7f8e16 d7e3b303761cb263d87f13f72ab60a958ec6eb21 M  Gemfile.lock
```

**Comment by patcon** [comment]
Awesome sleuthing man! git bisect is rad.

I'm thinkin it might have to do with your ruby-1.9.3 being compiled with an old version of xcode or something else critical that changed on your system. Both the gems and the base ruby should be compiled with all the same tools, so maybe `rvm remove 1.9.3` and compile it again anew? (by cd'ing into ariadne dir)

Hm. Having a specific ruby for ariadne (rather than just a gemset) kiiiinda solved this, because it forced a compilation of a new ruby on first install, and that's more likely to be the same compilers and associated tools that the gems will use. but the issue could still crop up regardless. We could move back if you think it's a good idea

**Comment by mparker17** [comment]
That worked.

Should I add this to the README, or should I start a troubleshooting page on the wiki?

**Comment by mparker17** [comment]
On second thoughts; the README file is getting REALLY big. I'm going to start a troubleshooting page on the wiki.

**Comment by mparker17** [comment]
Added [troubleshooting page](https://github.com/myplanetdigital/ariadne/wiki/Troubleshooting) to wiki.
