### ISSUE TITLE
Where did config.yml go?

### ISSUE THREAD

**Issue by nerdcorenet** [oriuminc/vagrant-ariadne#65]
So yesterday I could have sworn I had a config/config.yml, as I can see on my primary PC.

On another machine where I'm testing this project, I got "No such file or directory" on config/config.yml during 'vagrant up'. I'm blocked at this stage.

Where'd it go?

**Comment by patcon** [comment]
Ah, ok I'm guessing you moved to using `develop` branch? I took it out of version-control (because sensitive client names can be in the `project`, and we wouldn't want to accidentally commited). It's now generated in `rake setup`, so just run that again. It will only write it if it doesn't already exist.

Also, we moved it from `config/` to `roles/` in order to start getting it working on dedicated remote servers.

Since things will be changing kinda fast, maybe check out `CHANGELOG.md` if something changes unexpectedly. I'm trying to keep that up-to-date :)

**Comment by patcon** [comment]
Thanks again! Really appreciate the interest
